---
title: "Curriculum vitae"
---

You can download my current CV here: [Download CV](cv.pdf).

## Current position

**Lecturer**, School of Mathematics and Statistics, UNSW, 2026–present

## Education

- **PhD in Statistics**, University of New South Wales & CSIRO DATA61, 2025
- **1st Class Honours in Statistics**, University of New South Wales, 2017
- **Bachelor of Advanced Science (Major in Statistics, Minor in Marine Science)**, University of New South Wales, 2016

## Research funding and awards

- Peoples choice award for best presentation at UNSW Mathematics and Statistics Postgraduate Conference, 2024
- Tjanpi Award for best Student paper in Environmental Statistics (runner up), 2023
- 1st place in 1 minute thesis competition in the UNSW School of Mathematics and Statistics, 2022
- Australian Government Research Training program scholarship, 2021
- CSIRO Data61 PHD top up scholarship, 2021
- UNSW School of Mathematics and Statistics PHD top up scholarship, 2021

## Academic service

- Statistical Consultant Mentor in Statistical Consulting Session, Australian Statistical Conference, 2025
- Organisor for UNSW ecological statistics research group ecostats, 2021-2024

## Professional memberships

- Statistical Society of Australia ([SSA](https://www.statsoc.org.au/))
- Australian Society for Fish Biology ([ASFB](https://www.asfb.org.au/))

## Industry experience

**Statistical Consultant**, [Stats Central](https://www.unsw.edu.au/research/facilities-and-infrastructure/find-a-facility/stats-central), UNSW, 2018-2019, 2021-2026

Collaborated with over 220 academics, researchers, and higher degree research students at the University of New South Wales and partner institutions from a variety of disciplines to provide appropriate design and analysis advice relative to their research questions and data properties. I also regularly prepared content and facilitated seminars and courses on coding and statistical analysis methods for researchers and higher degree research students.

**Data Scientist**, [Wentworth Group of Concerned Scientists](https://wentworthgroup.org/), 2020, 2026

Applied statistical analysis to environmental policy questions for the Wentworth Group of Concerned Scientists, investigating changes in the outward flow and reliability of water shares under a drier climate in the Murray-Darling Basin and land clearing in NSW following 2016 environmental reforms.

**Statistical Insights Analyst**, [Healthdirect](https://www.healthdirect.gov.au/), 2020-2021

Developed reporting and advanced modelling insights to enhance the management of health and user experience data across a range of Healthdirect services.

**Data Analyst**, [Natural Resource Accesss Regulator](https://www.nrar.nsw.gov.au/), NSW Government, 2018-2019

Developed and implemented a reporting and data management system for the NSW Natural Resource Access Regulator. This enabled the tracking of workflow for the strategic management and triaging of tasks.
