---
title: "Publications | Ben Maslen"
bibliography: references.bib
csl: apa-reverse.csl
link-citations: true
nocite: |
  @*
---

## Software and data

**R package [ecopower](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://ftp.fau.de/cran/web/packages/ecopower/ecopower.pdf)** - Estimates power and performs equivalence testing for multivariate abundance data to answer ecological study design and habitat restoration questions. The software uses a Gaussian copula model for simulation, expert informed multivariate effect sizes, and a critical value based approach to estimating power. The package also provides functions for parameterising multivariate effect sizes and simulating multivariate abundance data jointly.

[**Tassie BRUV**](https://datadryad.org/dataset/doi:10.5061/dryad.sbcc2frf7)**: A benchmark data set for computer vision and movement quantification algorithms** (2025) - The Tassie BRUV dataset is an image dataset that we generated as a benchmark dataset using Baited Remote Underwater Videos (BRUVs) from chain moorings and environmentally friendly moorings in Tasmania. These videos were collected by CSIRO and OzFish volunteers as part of a separate study to observe if there are differences in the community abundance of fish species between chain and environmentally friendly moorings in this area. This dataset can be used to benchmark computer vision techniques, and, in conjunction with the surrounding video footage, techniques that include movement information.

## Preprints

Tripovich, J. S., Appleby, D., Nelson, C. M. V., Xu, Z., Klinck, H., Roe, P., Pitcher, B.J., Maslen, B. (2026). Monitoring bird acoustic activity in the Samford Valley, Queensland: Impacts of 2019–20 Black Summer Fires. Queensland: Impacts of, 20. Available at SSRN: <https://doi.org/10.2139/ssrn.7217945>

## Published research

::: {#refs}
:::
